# Generated by Django 3.2.8 on 2021-10-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_retailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
